name: Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium pytest chromedriver-autoinstaller

      - name: Install Google Chrome (using apt-get)
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Run Selenium tests
        run: pytest test_obj1_scenario1.py
