name: Selenium Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium pytest

      - name: Install unzip and Chrome dependencies
        run: |
          sudo apt update -y
          sudo apt install -y unzip google-chrome-stable

      - name: Check Chrome Version
        run: |
          google-chrome --version

      - name: Download ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1-3)
          echo "Chrome version is $CHROME_VERSION"
          # Fetch matching ChromeDriver version
          DRIVER_VERSION=$(curl -sSL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
          echo "ChromeDriver version is $DRIVER_VERSION"
          # Download and install the correct ChromeDriver version
          wget -q "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Check ChromeDriver Version
        run: |
          chromedriver --version

      - name: Set Chrome options for headless mode
        run: |
          echo "CHROME_BIN=/usr/bin/google-chrome-stable" >> $GITHUB_ENV
          echo "CHROME_DRIVER=/usr/local/bin/chromedriver" >> $GITHUB_ENV

      - name: Run Selenium tests
        run: |
          pytest test_obj1_scenario1.py --headless
