name: Selenium Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium pytest

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          wget -q "https://chromedriver.storage.googleapis.com/134.0.6998.165/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Set Chrome options for headless mode
        run: |
          echo "CHROME_BIN=/usr/bin/google-chrome-stable" >> $GITHUB_ENV
          echo "CHROME_DRIVER=/usr/local/bin/chromedriver" >> $GITHUB_ENV

      - name: Run Selenium tests
        run: |
          pytest test_obj1_scenario1.py --headless
