name: Selenium Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium pytest

      - name: Install unzip and Chrome dependencies
        run: |
          sudo apt update -y
          sudo apt install -y unzip google-chrome-stable

      - name: Check Chrome Version
        run: |
          google-chrome --version

      - name: Download ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1-3)
          echo "Chrome version is $CHROME_VERSION"
          # Fetch matching ChromeDriver version
          DRIVER_VERSION=$(curl -sSL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")

          # Debugging step: print DRIVER_VERSION
          echo "Attempting to fetch ChromeDriver version for $CHROME_VERSION: $DRIVER_VERSION"

          # If no exact driver found, fallback to latest stable release
          if [ -z "$DRIVER_VERSION" ]; then
            echo "Exact version not found. Falling back to the latest stable release."
            DRIVER_VERSION=$(curl -sSL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          fi

          # Debugging step: print DRIVER_VERSION after fallback
          echo "Using ChromeDriver version: $DRIVER_VERSION"

          if [ -z "$DRIVER_VERSION" ]; then
            echo "Failed to fetch ChromeDriver version. Exiting."
            exit 1
          fi

          # Download and install the correct ChromeDriver version
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/linux64/chrome-linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Check ChromeDriver Version
        run: |
          chromedriver --version

      - name: Set Chrome options for headless mode
        run: |
          echo "CHROME_BIN=/usr/bin/google-chrome-stable" >> $GITHUB_ENV
          echo "CHROME_DRIVER=/usr/local/bin/chromedriver" >> $GITHUB_ENV

      - name: Run Selenium tests
        run: |
          pytest test_obj1_scenario1.py --headless
