name: Selenium Tests with Preinstalled Chrome

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest

      - name: Check Installed Chrome & ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run Selenium Tests
        run: pytest test_obj1_scenario1.py  # Removed --headless
