name: Selenium Tests with Preinstalled Chrome

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest

      - name: Check Installed Chrome & ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version
          
      - name: Create test-results directory
        run: mkdir -p test-results

      - name: Run Selenium Tests
        run: pytest test_obj1_scenario1.py --junitxml=test-results/junit.xml | tee test_results.log

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            test-results/
            screenshots/
  
      - name: Publish Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: SauceDemo Tests
          path: "test-results/junit.xml"
          reporter: java-junit
          fail-on-error: false
