name: Run Selenium Tests in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Run Docker Container for Selenium Tests
        run: |
          # Build the Docker image
          docker build -t selenium-tests .

          # Run the tests inside the container
          docker run --rm selenium-tests
